"""stage2 intelligence state

Revision ID: 3d1c6a99d8c4
Revises: 0001_stage1_core
Create Date: 2026-08-28 02:01:04.700851
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d1c6a99d8c4'
down_revision: Union[str, Sequence[str], None] = '0001_stage1_core'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_mastery',
    sa.Column('mastery_id', sa.String(length=150), nullable=False),
    sa.Column('learner_id', sa.String(length=100), nullable=False),
    sa.Column('knowledge_point', sa.String(length=160), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('recent_accuracy', sa.Float(), nullable=False),
    sa.Column('common_errors', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mastery_id'),
    sa.UniqueConstraint('learner_id', 'knowledge_point', name='uq_mastery_learner_point')
    )
    op.create_index(op.f('ix_learner_mastery_learner_id'), 'learner_mastery', ['learner_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('version_id', sa.String(length=150), nullable=False),
    sa.Column('document_id', sa.String(length=150), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('parser', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.document_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('factory_jobs',
    sa.Column('job_id', sa.String(length=150), nullable=False),
    sa.Column('document_id', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.document_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_factory_jobs_document_id'), 'factory_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_factory_jobs_status'), 'factory_jobs', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.String(length=150), nullable=False),
    sa.Column('document_id', sa.String(length=150), nullable=False),
    sa.Column('version_id', sa.String(length=150), nullable=False),
    sa.Column('parent_section', sa.String(length=300), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.document_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.version_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_version_id'), 'knowledge_chunks', ['version_id'], unique=False)
    op.create_table('question_revisions',
    sa.Column('revision_id', sa.String(length=150), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=150), nullable=True),
    sa.Column('job_id', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('draft_payload', sa.JSON(), nullable=False),
    sa.Column('judge_decision', sa.JSON(), nullable=False),
    sa.Column('rewrite_instruction', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['factory_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index(op.f('ix_question_revisions_job_id'), 'question_revisions', ['job_id'], unique=False)
    op.create_index(op.f('ix_question_revisions_parent_revision_id'), 'question_revisions', ['parent_revision_id'], unique=False)
    op.create_index(op.f('ix_question_revisions_status'), 'question_revisions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_revisions_status'), table_name='question_revisions')
    op.drop_index(op.f('ix_question_revisions_parent_revision_id'), table_name='question_revisions')
    op.drop_index(op.f('ix_question_revisions_job_id'), table_name='question_revisions')
    op.drop_table('question_revisions')
    op.drop_index(op.f('ix_knowledge_chunks_version_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_factory_jobs_status'), table_name='factory_jobs')
    op.drop_index(op.f('ix_factory_jobs_document_id'), table_name='factory_jobs')
    op.drop_table('factory_jobs')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_learner_mastery_learner_id'), table_name='learner_mastery')
    op.drop_table('learner_mastery')
    # ### end Alembic commands ###
