import type {
  AuditLog,
  DashboardPayload,
  ModelProfile,
  Question,
  SkillDefinition,
} from './types'

export const safetyNotice = '仅供教学研修或医生复核前辅助，不作为独立诊断依据。'

export const mockQuestions: Question[] = [
  {
    id: 'q001',
    title: '胃窦黏膜基础识别',
    image_url: '/assets/real_samples/kv_cla820gl0s3nv071u4fgd7xgq.jpg',
    image_placeholder: '真实公开内镜样例：胃窦黏膜轻度发红，局部可见浅表糜烂样改变。',
    case_summary: '教学样例。医生需要先判断是否存在可描述的黏膜异常，而不是直接下诊断。',
    question: '从该内镜教学图像中，最合适的初步观察结论是？',
    options: ['可见局部黏膜发红/浅表糜烂样改变', '明确早期胃癌', '食管静脉曲张破裂', '证据不足，无法描述任何异常'],
    answer: '可见局部黏膜发红/浅表糜烂样改变',
    explanation: '图像支持描述局部黏膜发红和浅表糜烂样改变，但不能据此给出明确肿瘤诊断。',
    complexity: 1,
    question_class: '基础识别',
    source_type: '教学样例',
    atomic_trace: [
      {
        id: 'q001_f1',
        fact: '画面中存在黏膜颜色改变',
        expected: '应识别为可描述异常',
        supported: true,
        evidence: '视野中央偏右区域较周围更红',
        skill_dimension: '病灶识别',
      },
      {
        id: 'q001_f2',
        fact: '不能单凭该图给出恶性诊断',
        expected: '应保留不确定性',
        supported: true,
        evidence: '缺少病理、染色放大或连续视角',
        skill_dimension: '证据不足识别',
      },
    ],
    false_premise_flag: false,
    teaching_tags: ['黏膜观察', '观察依据', '基础识别'],
    difficulty: '入门',
    doctor_review_required: true,
    safety_notice: safetyNotice,
    body_part: '胃',
    task: '图像观察',
    question_type: '单选',
    source_dataset: '平台教学样例',
    citation_note: '平台脱敏教学样例。',
    is_favorited: false,
    review_status: '未开始',
    ai_benchmark_answer: '可见局部黏膜发红/浅表糜烂样改变',
    expected_keywords: ['黏膜', '发红', '糜烂', '观察依据'],
  },
  {
    id: 'q005',
    title: '报告纠错：图中是否一定有息肉',
    image_url: '/assets/real_samples/x1_cl8k2u1qa1ekz08324rek2qcv.jpg',
    image_placeholder: '真实公开内镜样例：可见黏膜发红，无明确息肉蒂或隆起边界。',
    case_summary: '题干故意诱导过度推断，医生需要回到图像观察依据。',
    question: '题干称“该息肉的大小最可能是多少”，你应如何处理？',
    options: ['指出证据不足：图中未明确显示息肉', '估计为2厘米并建议切除', '默认存在息肉并选择最大值', '直接判断为腺瘤'],
    answer: '指出证据不足：图中未明确显示息肉',
    explanation: '题干预设了图像未支持的息肉前提，正确做法是识别过度推断并说明观察依据不足。',
    complexity: 2,
    question_class: '报告纠错',
    source_type: '教学样例',
    atomic_trace: [
      {
        id: 'q005_f1',
        fact: '题干假设存在息肉',
        expected: '先验证前提',
        supported: false,
        evidence: '未见明确隆起、蒂部或边界',
        skill_dimension: '证据不足识别',
      },
      {
        id: 'q005_f2',
        fact: '不应凭空估计大小',
        expected: '拒绝无依据测量',
        supported: true,
        evidence: '单帧无测量标尺且目标不明确',
        skill_dimension: '数量判断',
      },
    ],
    false_premise_flag: true,
    teaching_tags: ['过度推断', '观察依据不足', '报告纠错'],
    difficulty: '进阶',
    doctor_review_required: true,
    safety_notice: safetyNotice,
    body_part: '胃',
    task: '过度推断识别',
    question_type: '单选',
    source_dataset: '平台教学样例',
    citation_note: '平台脱敏教学样例。',
    is_favorited: true,
    review_status: '待复盘',
    ai_benchmark_answer: '指出证据不足：图中未明确显示息肉',
    expected_keywords: ['证据不足', '息肉', '前提', '复核'],
  },
]

export const mockModels: ModelProfile[] = [
  {
    id: 'm_mock_tutor',
    name: '平台智能助手',
    provider_type: 'mock',
    model_family: '内镜领域',
    recommended_roles: ['智能辅导', '错因分析', '安全演示'],
    risk_tags: ['规则模板', '无真实临床评测', '医生复核'],
    ability_scores: { basic_recognition: 88, complex_reasoning: 78, false_premise: 91, chinese_report: 84, engineering: 94 },
    grade: 'A',
    is_active: true,
  },
  {
    id: 'm_domain_qwen',
    name: '微调模型 Qwen',
    provider_type: 'local',
    model_family: '内镜领域',
    recommended_roles: ['图像问答', '内镜专域对照'],
    risk_tags: ['微调模型', '需防幻觉', '待真实评测'],
    ability_scores: { basic_recognition: 86, complex_reasoning: 79, false_premise: 72, chinese_report: 76, engineering: 80 },
    grade: 'A',
    is_active: false,
  },
]

export const mockDashboard: DashboardPayload = {
  today_training: { completed: 6, target: 12, streak_days: 5, review_queue: 3 },
  learner_profile: {
    learner_id: 'demo_learner',
    name: '林知远 医师',
    title: '消化内镜进修医师',
    department: '消化内镜中心',
    hospital: '示范教学医院',
    training_stage: '进阶规范化研修第 3 周',
    training_goal: '提升观察依据、病灶属性判断和结构化报告表达能力',
    total_questions: 18,
    accuracy: 0.72,
    completed_today: 6,
    daily_target: 12,
    streak_days: 5,
    favorite_questions: ['q005'],
    wrong_questions: ['q005', 'q008', 'q013'],
    skill_scores: { 病灶识别: 78, 部位定位: 82, 属性判断: 70, 数量判断: 66, 事实组合: 74, 证据不足识别: 58 },
    weakness_tags: ['证据不足', '过度推断', '报告安全'],
    recent_errors: ['q005', 'q008', 'q013'],
    recommended_question_classes: ['报告纠错', '一图多问', '病变属性'],
    growth_trend: [
      { date: '05-28', accuracy: 63, evidence: 50, report: 66 },
      { date: '05-29', accuracy: 66, evidence: 53, report: 68 },
      { date: '06-01', accuracy: 72, evidence: 58, report: 74 },
    ],
    training_records: [
      { date: '2026-06-02', question_id: 'exam_seed_session', score: 67, result: '考试Session 3题/67%' },
      { date: '2026-06-02', question_id: 'q005', score: 35, result: '待复盘' },
      { date: '2026-06-01', question_id: 'q001', score: 100, result: '正确' },
    ],
    exam_sessions: [
      {
        id: 'exam_session_seed',
        session_id: 'exam_seed_session',
        date: '2026-06-02',
        answered_count: 3,
        correct_count: 2,
        accuracy: 67,
        average_score: 67,
        wrong_questions: ['q005'],
        elapsed_seconds: 418,
        finished_reason: 'manual_submit',
        profile_updated: true,
        created_at: '2026-06-02T09:10:00Z',
      },
    ],
    question_type_coverage: { 单选: 12, 多选: 2, 判断: 2, 问答评分: 1, 报告修改: 1 },
    updated_at: '2026-06-02T09:00:00Z',
  },
  ability_radar: [
    { dimension: '病灶识别', score: 78 },
    { dimension: '部位定位', score: 82 },
    { dimension: '属性判断', score: 70 },
    { dimension: '数量判断', score: 66 },
    { dimension: '事实组合', score: 74 },
    { dimension: '证据不足识别', score: 58 },
  ],
  recommended_training: [
    { label: '过度推断复盘', count: 4 },
    { label: '一图多问', count: 4 },
    { label: '报告纠错', count: 3 },
  ],
  today_plan: [
    { label: '错题复盘', target: 4, status: '优先', href: '/practice' },
    { label: '综合题组', target: 3, status: '计时', href: '/practice' },
    { label: '报告表达研修', target: 2, status: '复盘', href: '/report' },
  ],
  continue_training: {
    question_id: 'q005',
    title: '报告纠错：图中是否一定有息肉',
    source_dataset: '平台教学样例',
    reason: '根据最近错因优先复盘证据不足与过度推断。',
  },
  favorite_count: 1,
  wrong_count: 3,
  recent_tutor_summary: ['先描述可观察事实，再判断题干前提是否成立。', '报告复盘建议：避免把单帧图像所见写成最终诊断。'],
  growth_trend: [
    { date: '05-28', accuracy: 63, evidence: 50, report: 66 },
    { date: '05-29', accuracy: 66, evidence: 53, report: 68 },
    { date: '06-01', accuracy: 72, evidence: 58, report: 74 },
  ],
  active_model: mockModels[0],
  model_admission_state: {
    updated_at: '2026-06-02T16:00:00Z',
    last_admission_id: 'demo_seed',
    provider_name: '平台智能助手',
    grade: 'A',
    total_score: 82,
    mode: 'rule',
    provider_called: false,
    is_mock: true,
    tested_samples: ['platform_sample_0', 'platform_sample_1'],
    risk_items: ['初始状态为规则准入草案，未代表真实临床评测。'],
    recommendation: '输入临时模型信息后，可运行一次小样本研修能力探测。',
    safe_for_training: false,
  },
  platform_readiness: {
    generated_at: '2026-06-02T16:00:00Z',
    overall_score: 58,
    backend_ready: false,
    provider_ready: false,
    provider_mode: 'preview',
    knowledge_ready: true,
    memory_ready: true,
    qbank_count: 2,
    real_sample_count: 0,
    real_sample_coverage: {
      source_file: 'real_sample_knowledge.json',
      local_data_hint: 'E:\\2.Projects\\ARIS\\VQA\\data',
      total_records: 0,
      mapped_question_count: 0,
      asset_checked_count: 0,
      asset_present_count: 0,
      missing_assets: [],
      dataset_distribution: [],
      use_distribution: [],
      complexity_distribution: [],
      sample_ids: ['后端联通后显示'],
      coverage_note: '当前为本地预览；后端联通后会显示平台内镜数据资源的抽样数量、用途分布和图片资产校验。',
    },
    report_template_count: 2,
    training_record_count: 2,
    exam_session_count: 1,
    latest_exam_replay: {
      id: 'exam_session_seed',
      session_id: 'exam_seed_session',
      date: '2026-06-02',
      answered_count: 3,
      correct_count: 2,
      accuracy: 67,
      average_score: 67,
      wrong_count: 1,
      wrong_questions: ['q005'],
      elapsed_seconds: 418,
      profile_updated: true,
      created_at: '2026-06-02T09:10:00Z',
      href: '/practice',
      profile_href: '/profile?tab=records',
      status: '已写入画像',
      detail: '本场考试 3 题，正确率 67%，错题 1 题。',
    },
    audit_log_count: 1,
    admission_grade: 'A',
    admission_provider_called: false,
    knowledge_source_chain: [
      {
        id: 'real_sample_knowledge',
        label: '真实公开图文样例',
        source_file: 'real_sample_knowledge.json',
        record_count: 0,
        sample_ids: ['后端联通后显示'],
        used_by: ['研修题库', '报告中心', '模型评估'],
        proof: '当前为本地预览；后端联通后会显示平台图文样例如何映射到研修、报告和模型评估链路；不代表批量临床评测。',
        href: '/practice',
        tone: 'amber',
      },
      {
        id: 'report_knowledge_base',
        label: '诊断报告知识库',
        source_file: 'report_knowledge_base.json',
        record_count: 2,
        sample_ids: ['胃部炎症模板', '息肉风险表达模板'],
        used_by: ['报告草稿', '报告修改评分', '幻觉审查'],
        proof: '本地预览保留报告结构；后端在线后会进入报告草稿和复盘评分流程。',
        href: '/report',
        tone: 'green',
      },
      {
        id: 'card_template_knowledge',
        label: '科普卡片模板库',
        source_file: 'card_template_knowledge.json',
        record_count: 2,
        sample_ids: ['检查后说明卡', '复查提醒卡'],
        used_by: ['科普卡片草稿', '医生复核闸门', '分享/打印锁'],
        proof: '卡片草稿会标注模板知识库来源；医生复核前不会开放分享和打印。',
        href: '/report',
        tone: 'green',
      },
    ],
    evidence_receipts: [
      { id: 'real_sample_kb', label: '平台图文样例', status: '待联通', detail: '后端联通后会显示平台图文资源映射结果。', href: '/practice', tone: 'amber' },
      { id: 'practice_replay', label: '研修复盘', status: 'seed', detail: '种子研修记录可进入错题复盘。', href: '/practice', tone: 'green' },
      { id: 'report_kb', label: '报告知识库', status: 'ready', detail: '本地预览保留报告草稿结构。', href: '/report', tone: 'green' },
      { id: 'agent_status', label: '研修服务通道', status: 'preview', detail: '当前为本地预览，后端联通后显示完整研修能力。', href: '/models', tone: 'amber' },
      { id: 'model_probe', label: '模型轻量评估', status: 'not_run', detail: '启动后端后可在模型页运行临时评估。', href: '/models', tone: 'blue' },
      { id: 'practice_loop', label: '研修闭环', status: 'ready', detail: '研修、复盘、报告和画像可沿主流程演示。', href: '/practice', tone: 'green' },
      { id: 'profile_memory', label: '能力画像', status: 'seed', detail: '本地预览包含最近研修记录。', href: '/profile', tone: 'blue' },
    ],
    modules: [
      { id: 'backend_api', label: '后端服务', status: 'preview', detail: '后端断连时前端使用本地预览数据。', href: '/', tone: 'amber' },
      { id: 'real_samples', label: '平台图文样例', status: '待联通', detail: '后端联通后会加载平台统一内镜图文样例。', href: '/practice', tone: 'amber' },
      { id: 'practice_memory', label: '医师画像回灌', status: 'seed', detail: '本地演示画像包含研修记录和弱项标签。', href: '/profile', tone: 'blue' },
      { id: 'practice_replay', label: '研修复盘', status: 'seed', detail: '已有错题队列，可恢复复盘。', href: '/practice', tone: 'green' },
      { id: 'report_kb', label: '报告知识库', status: 'ready', detail: '报告模板与科普模板已可用于演示。', href: '/report', tone: 'green' },
      { id: 'agent', label: '智能助手', status: 'preview', detail: '后端联通后可显示完整模型评估结果。', href: '/models', tone: 'amber' },
      { id: 'profile', label: '能力画像', status: 'seed', detail: '本地预览包含画像成长记录。', href: '/profile', tone: 'blue' },
    ],
    demo_path: [
      { step: 1, title: '首页', detail: '确认平台定位和主流程。', href: '/', expected_state: '五入口清晰' },
      { step: 2, title: '模型评估', detail: '查看智能助手选择依据。', href: '/models', expected_state: '综合研修适配度' },
      { step: 3, title: '医生研修', detail: '完成图像题作答与证据复盘。', href: '/practice', expected_state: '作答 + 复盘' },
      { step: 4, title: '报告生成与修改', detail: '生成结构化草稿并修改表达。', href: '/report', expected_state: '报告草稿 + 修改' },
      { step: 5, title: '能力画像', detail: '查看医生研修成长。', href: '/profile', expected_state: '雷达 + 曲线' },
    ],
    gaps: ['当前为本地预览；启动后端后可查看完整平台状态。'],
    safety_notice: safetyNotice,
  },
  safety_notice: safetyNotice,
  mock_evaluation_notice: '模型能力分为平台评估预览，不代表真实临床结论。',
  reference_inspirations: ['平台统一内镜图像资源', '平台图像问答研修资源', '平台多模态解释能力参考'],
}

export const mockSkills: SkillDefinition[] = [
  { id: 'question_hint', name: '问题提示', description: '给出不泄露答案的提示。', category: 'training', enabled: true, risk_level: 'low', input_schema: {}, output_schema: {} },
  { id: 'atomic_feedback', name: '证据点反馈', description: '把错因映射到可复盘的图像证据点。', category: 'feedback', enabled: true, risk_level: 'medium', input_schema: {}, output_schema: {} },
  { id: 'false_premise_guard', name: '前提鲁棒校验', description: '识别证据不足、题干预设和不适用。', category: 'safety', enabled: true, risk_level: 'high', input_schema: {}, output_schema: {} },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit_mock_001',
    event_type: 'question_view',
    user_id: 'demo_learner',
    entity_id: 'q001',
    summary: '查看胃窦黏膜基础识别题。',
    risk_level: 'low',
    doctor_review_required: true,
    created_at: '2026-06-02T09:01:00Z',
  },
]
